# /models/itinerary.py
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Literal


class Message(BaseModel):
    role: Literal["user", "assistant", "system", "tool"]
    content: str

class TripSlots(BaseModel):
    # Added origin, keeping it optional for domestic trips starting from home location.
    origin: Optional[str] = None 
    destination: Optional[str] = None
    start_date: Optional[str] = None  # ISO date
    end_date: Optional[str] = None    # ISO date
    budget: Optional[str] = None      # Accept as string for LLM friendliness
    party: Optional[str] = None
    # Ensure interests is a list of strings
    interests: Optional[List[str]] = Field(default_factory=list) 
    
    # NEW: Add a flag for explicit domestic/international context, though domestic is default
    trip_type: Literal["domestic", "international"] = "domestic" # Enforcing your constraint

class ItinerarySegment(BaseModel):
    """A single segment in a day (e.g., flight, hotel check-in, museum visit)."""
    segment_type: Literal["flight", "lodging", "activity", "transport", "meal"]
    name: str
    start_time: Optional[str] = Field(None, description="ISO time or HH:MM format")
    end_time: Optional[str] = None
    duration_hours: Optional[float] = None
    notes: Optional[str] = None
    
    # References to the source data filled by specialist agents
    candidate_id: Optional[str] = Field(None, description="ID of the option from the candidates pool (e.g., specific flight ID)")


class ItineraryDay(BaseModel):
    """The detailed plan for a single day."""
    date: str = Field(..., description="ISO date (YYYY-MM-DD)")
    segments: List[ItinerarySegment] = Field(default_factory=list)
    daily_theme: Optional[str] = Field(None, description="e.g., 'Arrival & City Exploration' or 'Museum Day'")


class Itinerary(BaseModel):
    """The overall itinerary draft, generated by the Planner Agent."""
    destination: str
    start_date: str
    end_date: str
    status: Literal["Slots Extracted", "Draft Generated", "Bundled", "Needs Clarification"] = "Slots Extracted"
    daily_plans: List[ItineraryDay] = Field(default_factory=list)
    
    # Key output for the Planner: The full plan structure.
    
    
# Re-define ItineraryDay from state.py to use the stronger segment model:
# (If ItineraryDay was previously in state.py, remove it there and use this version)
# class ItineraryDay(BaseModel):
#     date: Optional[str] = None
#     items: List[Dict[str, Any]] = Field(default_factory=list) 

# You may also want a Preferences model for /models/preferences.py, but for now, 
# a Dict in AppState is sufficient until you build the actual learning logic.